---
title: DocOps Lab Git Commits Style Guide
docs-group: technical
description: "Protocols for authoring Git commits for DocOps Lab projects"
order: 66
---
include::../_local_settings.adoc[]
= Git Commits Style Guide
// tag::commit-styles[]
This document outlines the protocols for authoring Git commit messages in DocOps Lab projects.


[[general-style]]
== General Style

DocOps Lab _loosely_ follows the link:https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits] specification for Git commit messages.

Enforcement is not strict, but using modified Conventional Commits style is encouraged for consistency and clarity.

[NOTE]
Most DocOps Lab projects do not base Changelog/Release Notes generation on commit messages.

The basic outline for a Conventional Commit message is:

....
<type>[optional scope]: <summary>

[optional body]

[optional footer(s)]
....


[[commit-summary]]
== Commit Summary

The commit description should be concise and to the point, summarizing the change in 50 characters or less.

Use the imperative mood (e.g., "Add feature X" instead of "Added feature X").


[[commit-types]]
== Commit Types

// tag::commit-types[]
* Use imperative verbs ("`Add widget`", not "`Added`" or "`add`")
* `create: ...` for new docs or UI content
* `edit: ...` for minor edits to docs or UI content
* `feat: ...` for new features OR improvements
* `fix: ...` for bugfixes
* `chore: ...` for version bumps and sundry tasks with no product impact
* `test: ...` for test code changes
* `refactor: ...` for code restructuring with no functional changes
* `style: ...` for formatting, missing semi-colons, etc; no functional changes
* `perf: ...` for performance improvements
* `auto: ...` for changes to CI/CD pipelines and build system
* `revert: ...` for reverting previous changes
// end::commit-types[]


[[commit-body-conventions]]
== Commit Body Conventions
// tag::body-conventions[]
* Use the body to explain what and why vs. how.
* Reference issues and pull requests as needed.
* Use bullet points (`- text`) and paragraphs as needed for clarity.
* Do not hard-wrap lines, but _do_:
** use 1-sentence per line
** keep sentences short
// end::body-conventions[]

// end::commit-styles[]