---
title: GitHub Issues Types and Tasks Reference
docs-group: technical
slug: github-issues
description: "Tracking work for DocOps Lab projects"
order: 57
---
include::../_local_settings.adoc[]
= GitHub Issues Types and Tasks

include::../partials/_github-issues.adoc[]

See {xref_docs_github-issues-usage_link} for more about managing issues in DocOps Lab projects.


// tag::issue-types[]
[[issue-types]]
== Issue Types

Task::
A specific piece of work that does not directly lead to a change to the product.
Used for research, infrastructure management, and other sundry/chore tasks not necessarily associated with repository code changes.

Bug::
Reports describing unexpected behavior or malfunctions in the product.
Bug issues are used directly and become bugfixes (no technical type change) once resolved.

Feature::
Requests or ideas for new functionality in the product.

Improvement::
Enhancements of existing features or capabilities.

Epic::
An issue or collection of issues with a common goal that may involve work performed across release versions ("`milestones`").
// end::issue-types[]


// tag::issue-labels[]
[[issue-labels]]
== Issue Labels

All DocOps Lab projects use a common convention around GitHub issue labels to categorize and manage issues.

[[project-specific-labels]]
=== Project-specific Labels

`component:<part>`::
Label prefix for arbitrarily named product aspects, modules, interfaces, or subsystems.
Common components include `component:docker`, `component:cli`, and `component:docs` (see next section).
These correspond to the `part` property in ReleaseHx change records.

[[standard-documentation-labels]]
=== Standard Documentation Labels

`component:docs`::
Indicates the issue pertains to documentation infrastructure, layout, deployment, but not core content.

`documentation`::
The issue relates to documentation _content_ updates or improvements.

// tag::docs-labels[]
`needs:docs`::
The issue requires documentation updates as part of its resolution.
Documentation updates will likely be in a sub-issue with a `documentation` label.

`needs:note`::
The issue requires a note in the release history when resolved.
Release notes are appended to the description body     under `## Release Note`.

`changelog`::
The issue summary should be included in the changelog for the next release, even if no release note is included.
// end::docs-labels[]

[[admonition-labels]]
=== Admonition Labels

`REMOVAL`::
Removes functionality or features.

`DEPRECATION`::
Announces planned removal of functionality or features in a future release.
(Only appropriate for `documentation` issues.)

`BREAKING`::
Includes one or more changes that are not backward-compatible.

`SECURITY`::
Addresses or documents a security vulnerability or risk.

[[other-standard-labels]]
=== Other Standard Labels

`question`::
User or community member inquiries about the product or project.

`priority:high`::
Indicates that the issue is important and should be prioritized for release as soon as possible.

`priority:low`::
The issue is not urgent and can be addressed in a future release.

`priority:stretch`::
Issue is slated for the next release but can be bumped if it's holding up releasee.

`wontfix`::
The issue will not be addressed.
Comment from maintainers should explain why.

`duplicate`::
The issue is a duplicate of another issue, which should be linked in the comments.

`posted-by-issuer`::
Indicates that the issue was created by the Issuer tool.

`good first issue`::
Designates an issue suitable for new contributors to the project.

`help wanted`::
Indicates that maintainers are seeking assistance from the community to resolve the issue.
// end::issue-labels[]