---
permalink: /docs/agent/schemagraphy-sgyml/
indexed: false
---
include::../_agent_settings.adoc[]
= SchemaGraphy/SGYML 101

SGYML stands for SchemaGraphy YAML-based Modeling Language, a format designed, standardized, and maintained by DocOps Lab.

It is a specialized YAML preprocessing syntax that provides:

* A human-readable schema model that can define, govern, and parse the structure and contents of complex data objects and text documents alike

* An extension for YAML documents to incorporate new properties like `$ref` transclusion directives and inheritance/overlay properties

* A standardization around a base subset of YAML capabilities to constrain the complexity of YAML documents and support thereof

* Highly semantic data-typing to replace YAML's clunky model

SchemaGraphy Schemas and the SGYML and tooling to support them are in a nascent stage, still under development.

Check {xref_projects_schemagraphy_link} for the latest information on SchemaGraphy and SGYML.

[TIP]
If the codebase you are working on uses SGYML or SchemaGraphy Schemas, check for a path `../schemagraphy/` (relative to the project root).